telegram:
  bot:
    name: ${TELEGRAM_BOT_NAME}
    token: ${TELEGRAM_BOT_TOKEN}
    testtoken: ${TELEGRAM_BOT_TEST_TOKEN}

cbr:
  currency:
    rates:
      xml:
        url: ${CLIENT_XML_URL}

spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    from: ${MAIL_FROM}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: ${MAIL_HOST}


